In [1]:
import numpy as np

T = np.array([[0.9, 0.1],
              [0.5, 0.5]])

In [2]:
#T after 3 steps 
T_3 = np.linalg.matrix_power(T, 3)

In [3]:
T_50 = np.linalg.matrix_power(T, 50)

T_100 = np.linalg.matrix_power(T, 100)


In [4]:
T

array([[0.9, 0.1],
       [0.5, 0.5]])

In [5]:
print(T_3)
print(T_50)
print(T_100)

[[0.844 0.156]
 [0.78  0.22 ]]
[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]
[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]


In [9]:
v = np.array([[1.0, 0.0]])
v

array([[1., 0.]])

In [15]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Image/two_states_MDP.png", width=700, height=700)

In [17]:
print('After 1 iteration: ', np.dot(v,T))
print('After 3 iterations: ',np.dot(v,T_3))
print('After 50 iterations: ', np.dot(v,T_50))
print('After 100 iterations: ', np.dot(v,T_100))

After 1 iteration:  [[0.9 0.1]]
After 3 iterations:  [[0.844 0.156]]
After 50 iterations:  [[0.83333333 0.16666667]]
After 100 iterations:  [[0.83333333 0.16666667]]


In [16]:
 Image(url= "Image/transition_iteration.png", width=700, height=700)